name: "24Six Music"
description: "24Six Jewish Music Streaming for Home Assistant"
version: "1.5.22"
slug: twentyfour_six
url: "https://github.com/chanochsussman-lgtm/ha-addon-24six"

init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

startup: services
boot: auto
watchdog: "http://[HOST]:[PORT:8484]/api/setup/status"

ports:
  8484/tcp: null
ingress: true
ingress_port: 8484
panel_icon: mdi:music-circle
panel_title: 24Six

homeassistant_api: true
hassio_api: true
hassio_role: default

options: {}
schema: {}

map:
  - data